# There's two ways to configure rclone:
# 1. Start the rclone-config service, start an interactive shell, and run 'rclone config'.
#     This can be done through the Dockge UI
# 2. Run `just config` to use the docker-compose run command and spin
#     up a temporary version of the main rclone container. This avoids the need
#     to use a separate config container but it also means that you'll need to
#     run this command over SSH to control docker.

# Start rclone service with docker-compose run
config:
    docker-compose run --rm --entrypoint /bin/sh rclone

listremotes:
    docker-compose run --rm --entrypoint rclone rclone listremotes

test:
    docker-compose run --rm --entrypoint rclone rclone version