services:
  tailscale:
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4096M
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      NVIDIA_VISIBLE_DEVICES: void
      TS_ACCEPT_DNS: "false"
      TS_AUTHKEY: ${AUTH_KEY}
      TS_AUTH_ONCE: "true"
      TS_HOSTNAME: truenas-scale
      TS_SOCKET: /var/run/tailscale/tailscaled.sock
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: "false"
      TZ: ${TZ}
      UMASK: "002"
      UMASK_SET: "002"
    group_add:
      - 1000
      - 568
    healthcheck:
      interval: 30s
      retries: 5
      start_interval: 2s
      start_period: 15s
      test: tailscale status
      timeout: 5s
    image: ghcr.io/tailscale/tailscale:latest
    network_mode: host
    platform: linux/amd64
    privileged: false
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    stdin_open: false
    tty: false
    volumes:
      # this volume is for general tailscale data. By saving it on the NAS,
      # we can restore the tailscale server state without needing to re-auth:
      - ${DATA_DIR}:/var/lib/tailscale
      # this volume is for the socket. It allows other containers to access the
      # tailscale daemon. Caddy in particular needs this.
      - /var/run/tailscale:/var/run/tailscale
networks: {}
